
backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhoud", name: "body", widget: "markdown" }
